### PR TITLE
cursor plugin: fix crash when destroy triggered before ready

### LINKED ISSUE #2602: cursor plugin: crash when destroy triggered before ready
we don't provide support for React; take a look at https://www.npmjs.com/package/wavesurfer-react instead.

_Originally posted by @thijstriemstra in https://github.com/katspaugh/wavesurfer.js/issues/2563#issuecomment-1286889167_

### PR DESCRIPTION
**Pull request by SilvaQ**
### Related Issues and other PRs:
fixes #2602

### CODE REVIEW

File: src/plugin/cursor/index.js [hunk 1]
```diff
@@ -322,8 +333,7 @@ export default class CursorPlugin {
      * @returns {string} Formatted timestamp
      */
     formatTime(cursorTime) {
-        cursorTime = isNaN(cursorTime) ? 0 : cursorTime;
-
+        cursorTime = isNaN( cursorTime ) ? 0 : cursorTime;
```
Comment (thijstriemstra) [inline src/plugin/cursor/index.js:336]: no need to add extra whitespace here

File: src/plugin/cursor/index.js [hunk 2]
```diff
@@ -17,6 +17,7 @@
  * the cursor follow the x and the y-position of the mouse. Use `false` to make the
  * it only follow the x-position of the mouse.
  * @property {function} formatTimeCallback Formats the timestamp on the cursor.
+ * @property {boolean} isDestroyCalled  true if call destory before ready event
```
Comment (thijstriemstra) [inline src/plugin/cursor/index.js:20]: `true if called destroy before the ready event fired`

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
thanks, see inline comments. can you also add a changelog entry?
