### PR TITLE
throw error when invalid url is passed to MediaElement backend

### LINKED ISSUE #1773: Calling load() without arguments throws error
calling `wavesurfer.load()` without params should not throw an error:

```javascript
var surfer = new WaveSurfer({
        backend: 'MediaElement',
        container: '#waveform'
      });

surfer.load();
```

Error
```
TypeError: this.backend is null
```

### PR DESCRIPTION
**Pull request by thijstriemstra**
follow-up to #1774 

fixes #1773

### CODE REVIEW

File: src/mediaelement.js [hunk 1]
```diff
@@ -135,6 +139,14 @@ export default class MediaElement extends WebAudio {
             media.load();
         }
 
+        // verify media element
+        if (
+            !(media instanceof HTMLMediaElement) ||
+            media.addEventListener === undefined
```
Comment (aburai) [inline src/mediaelement.js]: i prefer typeof check for undefined
and should the verify be on top of the _load method? i am not sure

Comment (thijstriemstra) [reply src/mediaelement.js]: done
