### PR TITLE
Fix peaks rendering issue on zooming and scrolling multicanvas

### LINKED ISSUE #1261: Zoom erase or not rendered leftpart of the wave (without peaks) and rightpart (if peaks) when scrolling
Hi, 
In the last version 2.0.0-beta02 I find a regression between 2.0.0-beta01 whit the zoom.
When you zoom the wave, this action automaticly render the wave center at the read position (on pause to make the test).
Then left part of the wave is not visible, but you can see it whit scroll. In the last version , left part not visible will be lost, when you scrolling left there no wave :

image

No need code, I use the demo code to reproduce ([https://wavesurfer-js.org/examples/

](https://wavesurfer-js.org/examples/)) . Same issue in firefox quantum 57.0 and chrome  62.0.3202.94.

Hope this can help.

### LINKED ISSUE #1399: Zoom rendered and performance
Hi, 
Two issues : when I zoom on wavesrufer loaded with peaks, there are rendered issue : blank zone or duplicate peaks on new canvas depend of zoomLevel.

image
image

When increase zoom, there si bad performance rendered,
- on Chrome : [Violation] 'requestAnimationFrame' handler took xxxxms
- on FireFox : shutdown process and memory leak ! 

There currently existing rendering issue when zooming and scroll to get all peaks left and right : #1261 
See @jamiefaye and my solution to get all wave rendered.

I Need to merge solution between zooming and scrolling use and without this rendered and bad performance.

### Browser version(s):
Chrome v67, Firefox 60

### Code needed to reproduce the issue:
Apply zoom on waveform with peaks. I do this with mouse wheel and timeOut between scroll=>

```javascript
var zoomLevel;
wavesurfer.on('ready', function () {
// define inital zoom level
                    zoomLevel = Math.trunc(wavesurfer.drawer.getWidth() / wavesurfer.getDuration() / wavesurfer.params.pixelRatio);
                    wavesurfer.container.addEventListener('wheel', wheelZoomHandler);
                });
```

```javascript
var zoomStep = 2;
    var zoomTimeOut;
    // initialise start NO zoom 
 wavesurfer.zoom();
    function wheelZoomHandler(e) {
        var deltaY = 0;
        e.preventDefault();
        if (e.deltaY) { // FireFox 17+ (IE9+, Chrome 31+?)
            deltaY = e.deltaY;
        } else if (e.wheelDelta) {
            deltaY = -e.wheelDelta;
        }
        // Update the bg size:
        clearTimeout(zoomTimeOut);
        if (deltaY &lt; 0) {
                zoomLevel += zoomStep;
                zoomTimeOut = setTimeout(function(){
                    console.log('Zoom increase : ' + zoomLevel);
                    wavesurfer.zoom(zoomLevel);
                },200);
        } else {
            if (zoomLevel &gt; Math.trunc(wavesurfer.drawer.getWidth() / wavesurfer.getDuration() / wavesurfer.params.pixelRatio)){ 
                zoomLevel -= zoomStep;
                zoomTimeOut = setTimeout(function(){
                    console.log('Zoom decrease : ' + zoomLevel);
                    wavesurfer.zoom(zoomLevel); 
                },200);
            } else { // stay zoomlevel at start value
                zoomLevel = Math.trunc(wavesurfer.drawer.getWidth() / wavesurfer.getDuration() / wavesurfer.params.pixelRatio);
                wavesurfer.zoom(); // reinit no zoom
            }
        }
    };
```

### Use behaviour needed to reproduce the issue:

Load file with peaks (example of 30 minutes with little data per second)
Use mouse wheel to increase or decrease zoom and let see rendered, navigator and computer UC/memory  !

I'm working on a solution, but all idea and optimization are welcome ;-)

### PR DESCRIPTION
**Pull request by awenger63**
Here is my change code for issues:

fixes #1261 
fixes #1399

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@awenger63. Thanks. First of all, this PR has conflicts that must be resolved (src/drawer.multicanvas.js), can you take a look at that?

**Comment by awenger63** [comment]
@thijstriemstra OK, I would like to validate my change, but I think I don't have write access ? {Resolcve conflicts] only show conflicting file.
How can I validate conflict change ? => right change for me itis `const h = Math.round(peak / absmaxHalf);` 
This change it's only for optimization, each of them make same result.

**Comment by thijstriemstra** [comment]
you can resolve the conflict in your branch/PR, no need for write access.

**Comment by Bran1304** [comment]
Thanks @awenger63 I was just about to push a PR to fix this, but I noticed your one now :) I tested your solution and it seems to work perfectly, thanks!

**Comment by awenger63** [comment]
I'm really disappointed, but [Resolve conflicts] button open the file where I see conflict, but I cannot do any action for validate any change.

**Comment by Bran1304** [comment]
@awenger63 there are still some eslint errors from the `prettier` config it seems

**Comment by awenger63** [comment]
GRRRR !!!  Can someone have the right indentation and fix this 'cosmetic' issue. This program never happy :-(

**Comment by Bran1304** [comment]
@awenger63 For some reason I cannot create a PR to your fork, but here is the fix https://github.com/Bran1304/wavesurfer.js/commit/2cccfa1f9e0b123b1738314a27e939cc0fc55661

**Comment by awenger63** [comment]
What new issue ? Can I do something ?

**Comment by Bran1304** [comment]
Something for @thijstriemstra I guess

**Comment by thijstriemstra** [comment]
> GRRRR !!! Can someone have the right indentation and fix this 'cosmetic' issue. This program is never happy :-(

I'm also annoyed by the current eslint settings. If you can ease these rules in a pull request, we'll all be happier ;)

File: src/drawer.multicanvas.js [hunk 1]
```diff
@@ -106,8 +106,9 @@ export default class MultiCanvas extends Drawer {
      */
     updateSize() {
         const totalWidth = Math.round(this.width / this.params.pixelRatio);
+        // No need more canvas if it's only for 2 peaks (there the same for overlaps !)
         const requiredCanvases = Math.ceil(
-            totalWidth / this.maxCanvasElementWidth
+            totalWidth / (this.maxCanvasElementWidth + 2)
```
Comment (chrisparton1991) [inline src/drawer.multicanvas.js]: By "2 peaks", do you mean "2 pixels"?

**Comment by chrisparton1991** [comment]
Hey @thijstriemstra, it's been a looong time since I wrote the MultiCanvas stuff (pre-ES6 overhaul), but it looks fine from what I can see. I wasn't sure about one of the comments ("2 peaks" vs. "2 pixels") so I asked for clarification there.

**Comment by thijstriemstra** [comment]
> I wasn't sure about one of the comments ("2 peaks" vs. "2 pixels") so I asked for clarification there.

Thanks! Same here.

File: src/drawer.multicanvas.js (hunk 1 above)
Comment (awenger63) [reply src/drawer.multicanvas.js]: Hi @chrisparton1991 , I really say 2 peaks.
TotalWidth it's a pixelRatio, not a real pixel. Than number 2 it's for peaks and for caluted the number of canvas need.
You can see #1399 picture result have more then 2 pixels for 2 peaks.

Comment (katspaugh) [reply src/drawer.multicanvas.js]: So if I understood correctly, the extra pixel (or two subpixels) is a result of a rounding error somewhere in the zoom code?

Comment (awenger63) [reply src/drawer.multicanvas.js]: Not really a rounding Error, but this différence clearliy appear on Zoom process like my screen shot I have posted. Because zooming add a lot of canvas and error it's on the join position af the cnavas. Perha^ps @chrisparton1991 can explian this better than me, but in Multicanvas each canvas begin on same position of the end of previous canvas, than first peak it's the same than the last, and last it's the same of the first of the next. Thans if you just have same number of peaks

Comment (katspaugh) [reply src/drawer.multicanvas.js]: Gotcha! (I think)
If it works, then it works 👍
