### PR TITLE
Regions plugin - Scroll when near edges of container

### LINKED ISSUE #430: Dragging a region doesn't work outside of scrollbar
When I try to drag a region, with a part of that region inside view and a part outside of the view, I expect that the scrollbar moves with my mouse so I can select more that what's currently in view. Maybe the current behavior (selecting only inside view) is the expected behavior for others?

### PR DESCRIPTION
**Pull request by roboswank**
When dragging, if mouse or region edge is near the container's edges, scroll in that direction.

### Short description of changes:
Added checks, within region mouse move events, to scroll the container when within a certain threshold of the container's edges.

New region plugin options available:
`scroll` - defaults to true
`scrollSpeed` - defaults to 1
`scrollThreshold` - defaults to 10

### Related Issues and other PRs:
fixes #430

### CODE REVIEW

File: src/plugin/regions.js [hunk 1]
```diff
@@ -639,12 +780,25 @@ export default class RegionsPlugin {
                 region = this.add(params || {});
             }
```
Comment (roboswank) [inline src/plugin/regions.js]: Not sure if this really needs to be updated on each interaction - but moved it to `eventDown` so it is not being called on every mouse move.

**Comment by thijstriemstra** [comment]
@roboswank can you add a changelog item for this?
