### PR TITLE
throw error when url parameter is not supplied to load()

### LINKED ISSUE #1773: Calling load() without arguments throws error
calling `wavesurfer.load()` without params should not throw an error:

```javascript
var surfer = new WaveSurfer({
        backend: 'MediaElement',
        container: '#waveform'
      });

surfer.load();
```

Error
```
TypeError: this.backend is null
```

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #1773

### CODE REVIEW

File: src/wavesurfer.js [hunk 1]
```diff
@@ -1290,6 +1290,9 @@ export default class WaveSurfer extends util.Observer {
      * );
      */
     load(url, peaks, preload, duration) {
+        if (url === undefined) {
+            throw new Error('url parameter is invalid');
```
Comment (katspaugh) [inline src/wavesurfer.js]: Maybe `if (!url)` to also throw if it's an empty string or null?
The error message could then be `The URL parameter cannot be empty` or similar.

Comment (thijstriemstra) [reply src/wavesurfer.js]: sounds good, was struggling to find a good description for the error but that's a better check.

**Comment by thijstriemstra** [comment]
Also fixed error for calling `wavesurfer.destroy()`.
