### PR TITLE
fix: unawaited promises fixes #3126

### LINKED ISSUE #3126: Unawaited (dangling) promises in Decoder#decode, WaveSurfer#load, and WaveSurfer#loadBlob
Firstly, thanks for your work on this project! 🙂

There are unawaited (dangling) promises that cause an uncaught exception when the audio data cannot be decoded for some reason.

I used [patch-package](https://github.com/ds300/patch-package) to patch `wavesurfer.js@7.1.4` for the project I'm working on and here is the diff that solved my problem:

```diff
diff --git a/node_modules/wavesurfer.js/dist/decoder.js b/node_modules/wavesurfer.js/dist/decoder.js
index 05a4b74..143d340 100644
--- a/node_modules/wavesurfer.js/dist/decoder.js
+++ b/node_modules/wavesurfer.js/dist/decoder.js
@@ -12,8 +12,7 @@ function decode(audioData, sampleRate) {
     return __awaiter(this, void 0, void 0, function* () {
         const audioCtx = new AudioContext({ sampleRate });
         const decode = audioCtx.decodeAudioData(audioData);
-        decode.finally(() => audioCtx.close());
-        return decode;
+        return decode.finally(() => audioCtx.close());
     });
 }
 /** Normalize peaks to -1..1 */
diff --git a/node_modules/wavesurfer.js/dist/wavesurfer.js b/node_modules/wavesurfer.js/dist/wavesurfer.js
index 13ae5e4..ce6138a 100644
--- a/node_modules/wavesurfer.js/dist/wavesurfer.js
+++ b/node_modules/wavesurfer.js/dist/wavesurfer.js
@@ -200,13 +200,13 @@ class WaveSurfer extends Player {
     /** Load an audio file by URL, with optional pre-decoded audio data */
     load(url, channelData, duration) {
         return __awaiter(this, void 0, void 0, function* () {
-            this.loadAudio(url, undefined, channelData, duration);
+            yield this.loadAudio(url, undefined, channelData, duration);
         });
     }
     /** Load an audio blob */
     loadBlob(blob, channelData, duration) {
         return __awaiter(this, void 0, void 0, function* () {
-            this.loadAudio('blob', blob, channelData, duration);
+            yield this.loadAudio('blob', blob, channelData, duration);
         });
     }
     /** Zoom the waveform by a given pixels-per-second factor */
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by mfellner**
## Short description
Resolves #3126

## Checklist
* [ ] This PR is covered by e2e tests
* [x] It introduces no breaking API changes

### CODE REVIEW

File: src/decoder.ts [hunk 1]
```diff
@@ -2,8 +2,7 @@
 async function decode(audioData: ArrayBuffer, sampleRate: number): Promise<AudioBuffer> {
   const audioCtx = new AudioContext({ sampleRate })
   const decode = audioCtx.decodeAudioData(audioData)
-  decode.finally(() => audioCtx.close())
-  return decode
+  return decode.finally(() => audioCtx.close())
```
Comment (katspaugh) [inline src/decoder.ts:5]: This was not awaited on purpose. It's a side effect.

**Review by katspaugh — APPROVED** [review]
Thank you!
