### PR TITLE
Fix #745: Check seekTo progress parameter and return understandable error

### LINKED ISSUE #745: Failed to set the 'currentTime' property on 'HTMLMediaElement'
big wav file.1:20:32.wrong:
wavesurfer.js:1257 Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.

### PR DESCRIPTION
**Pull request by mspae**
### Short description of changes:
- Checks whether the progress parameter passed to `wavesurfer.seekTo` is
  - a number
  - not NaN
  - between 0 and 1

### Breaking in the external API:
/

### Breaking changes in the internal API:
/

### Todos/Notes:
Also includes the build fixing commit from #1233 in order to be able build.

### Related Issues and other PRs:
- "Fixes" #745 by providing a readable error message.
- "Fixes" #1228

### CODE REVIEW

File: src/wavesurfer.js [hunk 1]
```diff
@@ -739,6 +739,16 @@ export default class WaveSurfer extends util.Observer {
      * wavesurfer.seekTo(0.5);
      */
     seekTo(progress) {
+        if (
```
Comment (thijstriemstra) [inline src/wavesurfer.js]: can you add a comment here, this is hard to read.
