### PR TITLE
mediaelement: fix volume updates

### LINKED ISSUE #1615: MediaElement mute not updated
When you unmute the volume of an existing `<audio>` element, `wavesurfer.isMuted` is still `true`.

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #1615

### CODE REVIEW

File: src/mediaelement.js [hunk 1]
```diff
@@ -337,7 +346,7 @@ export default class MediaElement extends WebAudio {
      * @return {number} value A floating point value between 0 and 1.
      */
     getVolume() {
-        return this.volume || this.media.volume;
+        return this.volume;
```
Comment (thijstriemstra) [inline src/mediaelement.js]: this was a bugfix actually because it would never return `this.volume = 0` (resolves to `false`, unless `this.media.volume` was coincidentally 0 as well)
